import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'

test('App exposes capability contracts instead of the concrete Robot facade at the MOD boundary', () => {
  const capabilities = readFileSync('host/app/capabilities.ts', 'utf8')
  const appBehavior = readFileSync('host/app/default-behavior/behavior.ts', 'utf8')
  const wasmAppBehavior = readFileSync('host/app/default-behavior/wasm/behavior.ts', 'utf8')
  const behaviorTypes = readFileSync('host/app/app-behavior.ts', 'utf8')
  const main = readFileSync('host/app/main.ts', 'utf8')
  const compose = readFileSync('host/app/compose.ts', 'utf8')
  const runtimeContext = readFileSync('host/app/runtime-context.ts', 'utf8')
  const runtimeAudio = readFileSync('host/app/runtime-audio.ts', 'utf8')
  const runtimeUI = readFileSync('host/app/runtime-ui.ts', 'utf8')
  const motionController = readFileSync('host/modules/motion/motion-controller.ts', 'utf8')
  const manifest = JSON.parse(readFileSync('host/app/manifest.json', 'utf8'))
  const motionManifest = JSON.parse(readFileSync('host/modules/motion/manifest.json', 'utf8'))
  const motionWasmManifest = JSON.parse(readFileSync('host/modules/motion/manifest_wasm.json', 'utf8'))
  const wasmAppManifest = JSON.parse(readFileSync('host/app/manifest_wasm.json', 'utf8'))
  const wasmManifest = JSON.parse(readFileSync('host/platforms/wasm/manifest.json', 'utf8'))

  for (const capability of [
    'FaceCapability',
    'MotionCapability',
    'AudioCapability',
    'InputCapability',
    'LightingCapability',
    'CameraCapability',
    'ConversationCapability',
    'ConnectivityCapability',
    'UICapability',
    'StackchanContext',
  ]) {
    assert.match(capabilities, new RegExp(`export type ${capability}\\b`))
  }

  assert.match(behaviorTypes, /export type StackchanAppBehavior/)
  assert.doesNotMatch(behaviorTypes, /onRobotCreated/)
  assert.doesNotMatch(behaviorTypes, /behaviorFromMod/)
  assert.match(appBehavior, /import type \{ StackchanAppBehavior \} from 'app-behavior'/)
  assert.match(wasmAppBehavior, /import type \{ StackchanAppBehavior \} from 'app-behavior'/)
  assert.doesNotMatch(appBehavior, /from 'robot'/)
  assert.doesNotMatch(wasmAppBehavior, /from 'robot'/)

  assert.match(main, /const preferences = loadPreferenceConfig\(\)/)
  assert.match(main, /createStackchanContext\(preferences\)/)
  assert.doesNotMatch(main, /createRobot\(\)/)
  assert.match(compose, /export function createStackchanContext\(preferences: PreferenceConfig\): StackchanContext/)
  assert.match(compose, /new StackchanRuntimeContext\(/)
  assert.doesNotMatch(compose, /from 'robot'/)

  assert.ok(manifest.modules['*'].includes('./app-behavior'))
  assert.ok(manifest.modules['*'].includes('./capabilities'))
  assert.ok(manifest.modules['*'].includes('./runtime-audio'))
  assert.ok(manifest.modules['*'].includes('./runtime-camera'))
  assert.ok(manifest.modules['*'].includes('./runtime-context'))
  assert.ok(manifest.modules['*'].includes('./runtime-input'))
  assert.ok(manifest.modules['*'].includes('./runtime-lighting'))
  assert.ok(manifest.modules['*'].includes('./runtime-ui'))
  assert.ok(!manifest.modules['*'].includes('./runtime-motion'))
  assert.ok(!manifest.modules['*'].includes('../../stackchan/robot'))
  assert.ok(motionManifest.preload.includes('motion-controller'))
  assert.equal(motionWasmManifest.modules['motion-controller'], './motion-controller')
  assert.equal(manifest.modules['app-default-behavior'], './default-behavior/behavior')
  assert.equal(manifest.modules['app-behavior'], './app-behavior')
  assert.ok(wasmAppManifest.include.includes('../platforms/wasm/manifest.json'))
  assert.ok(wasmManifest.modules['*'].includes('../../app/app-behavior'))
  assert.ok(wasmManifest.modules['*'].includes('../../app/capabilities'))
  assert.ok(wasmManifest.modules['*'].includes('../../app/runtime-audio'))
  assert.ok(wasmManifest.modules['*'].includes('../../app/runtime-camera'))
  assert.ok(wasmManifest.modules['*'].includes('../../app/runtime-context'))
  assert.ok(wasmManifest.modules['*'].includes('../../app/runtime-input'))
  assert.ok(wasmManifest.modules['*'].includes('../../app/runtime-lighting'))
  assert.ok(wasmManifest.modules['*'].includes('../../app/runtime-ui'))
  assert.ok(!wasmManifest.modules['*'].includes('../../app/runtime-motion'))
  assert.ok(!wasmManifest.modules['*'].includes('../../stackchan/robot'))
  assert.equal(wasmManifest.modules['app-default-behavior'], '../../app/default-behavior/wasm/behavior')
  assert.equal(wasmManifest.modules['app-behavior'], '../../app/app-behavior')

  assert.doesNotMatch(runtimeContext, /createFaceState/)
  assert.doesNotMatch(runtimeContext, /SpeechBalloon/)
  assert.doesNotMatch(runtimeContext, /DrawerButtonSpec/)
  assert.doesNotMatch(runtimeContext, /#tts:/)
  assert.doesNotMatch(runtimeContext, /#driver:/)
  assert.doesNotMatch(runtimeContext, /#button:/)
  assert.doesNotMatch(runtimeContext, /#touch:/)
  assert.doesNotMatch(runtimeContext, /#touchPanel:/)
  assert.doesNotMatch(runtimeContext, /#imu:/)
  assert.doesNotMatch(runtimeContext, /#microphone:/)
  assert.doesNotMatch(runtimeContext, /#camera:/)
  assert.doesNotMatch(runtimeContext, /#tone:/)
  assert.doesNotMatch(runtimeContext, /#led:/)
  assert.doesNotMatch(runtimeContext, /#pose:/)
  assert.doesNotMatch(runtimeContext, /#gazePoint:/)
  assert.match(capabilities, /from 'motion-controller'/)
  assert.match(capabilities, /from 'tts-types'/)
  assert.match(capabilities, /stream: \(text: string, volume\?: number, callback\?: TTSCompletion\) => void/)
  assert.doesNotMatch(capabilities, /stream: \(text: string, volume\?: number\) => Promise<void>/)
  assert.doesNotMatch(capabilities, /export type Driver = MotionDriver/)
  assert.doesNotMatch(capabilities, /driver: Driver/)
  assert.match(capabilities, /pose: MotionControllerPose/)
  assert.match(runtimeContext, /from 'motion-controller'/)
  assert.match(runtimeAudio, /function waitForSpeech/)
  assert.match(runtimeAudio, /this\.#tts\.stream\(text, volume, callback\)/)
  assert.match(runtimeContext, /function waitForMotion/)
  assert.doesNotMatch(runtimeContext, /get driver\(\)/)
  assert.match(motionController, /export type MotionCompletion = \(error\?: unknown\) => void/)
  assert.match(motionController, /setPose\(pose: Pose, time\?: number, callback\?: MotionCompletion\): void/)
  assert.doesNotMatch(motionController, /async setPose/)
  assert.doesNotMatch(motionController, /setPose\(pose: Pose, time\?: number\): Promise<void>/)
  assert.match(runtimeContext, /#uiRuntime/)
  assert.match(runtimeContext, /#audioRuntime/)
  assert.match(runtimeContext, /#cameraRuntime/)
  assert.match(runtimeContext, /#inputRuntime/)
  assert.match(runtimeContext, /#lightingRuntime/)
  assert.match(runtimeContext, /#motionController/)
  assert.match(runtimeUI, /createFaceState/)
  assert.match(runtimeUI, /SpeechBalloon/)
  assert.match(runtimeUI, /DrawerButtonSpec/)
})
